name: k_anonymization
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - torch
    - pandas
    - numpy
    - tqdm
    - scikit-learn
    - itables==2.5.2
    - packaging
    - ipywidgets
    - "itables[widget]"
